title: Quran Themes
theme: minima
include: ['pages','articles']

collections:
  articles:
    output: true
    permalink: /:collection/:path
  pages:
    output: true
    permalink: /:collection/:path
